"""empty message

Revision ID: 029469365936
Revises: 
Create Date: 2019-05-09 16:57:30.796692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '029469365936'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('globalTweets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('tweets', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('globalTweets')
    # ### end Alembic commands ###
